### PR TITLE
added time blocks to HTML

### LINKED ISSUE #5: add html base elements to main index

### PR DESCRIPTION
**Pull request by bill6653**
added time blocks into html.

### CODE REVIEW

**Review by shwnsmith12 — APPROVED** [review]
Time Blocks added to HTML properly - Looks Good

**Review by mrjakeschultz — APPROVED** [review]
Good to go.

**Review by Khiaotic — COMMENTED** [review]
push  review

**Review by dianamacias1218 — APPROVED** [review]
:)

**Review by jsadowski7 — APPROVED** [review]
Looks good!

**Review by Khiaotic — APPROVED** [review]
looks nice

**Pull request merged**
