### PR TITLE
Feature/khi htmlstyling withautocomplete

### LINKED ISSUE #24: style up the about the about page, add css

### PR DESCRIPTION
**Pull request by Khiaotic**
added styling and needed links. NEED  TO HYPERLINK HOME BUTTON TO HOME PAGE AND SO ON

### CODE REVIEW

**Review by jsadowski7 — APPROVED** [review]
Looks good

**Review by jsadowski7 — APPROVED** [review]
yessssss

**Review by jsadowski7 — APPROVED** [review]
looks good!

**Review by shwnsmith12 — APPROVED** [review]
Updates look good!

**Review by dianamacias1218 — APPROVED** [review]

**Comment by jsadowski7** [comment]
Approved by all!

**Pull request merged**
